### ISSUE TITLE
내 정보 글씨체관련

### ISSUE THREAD

**Issue by kgh2120** [todoay/client-android#15]
aws 연동 테스트 하면서 기능 같은거 수정해보고 있었는데, 뭔가 글씨체가 너무 얇아서 잘 안보이는 느낌이 드네.
사진에서도 ! 같은 경우에 좀 흐려보이는 느낌이 있어서.. 좀 더 굵게 하는게 어떨까??
월요일 회의에서 이야기 해도 좋고
![image](https://user-images.githubusercontent.com/76154390/181782212-634a53ff-4f91-43a6-9056-5e8b54d174dc.png)

**Comment by hsh47607** [comment]
글자크기 수정해서 다시 올려볼게!
